skip_tags: true

matrix:
  fast_finish: true

os: Visual Studio 2015

environment:
  matrix:
    - PLATFORM: "x64"
      VCBUILD: "vcbuild64.bat"
      RUNTEST: "runtest64.bat"
      PYTHON: "C:\\Python35-x64"
    - PLATFORM: "x86"
      VCBUILD: "vcbuild32.bat"
      RUNTEST: "runtest32.bat"
      PYTHON: "C:\\Python35"

before_build:
  "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %PLATFORM%"

build_script:
  - git clone https://github.com/plures/ndtypes.git
  - cd ndtypes
  - "%PYTHON%\\python.exe setup.py install --local=..\\python"
  - cd ..\vcbuild
  - "%VCBUILD%"
  - "%RUNTEST%"
  - cd ..
  - "%PYTHON%\\python.exe setup.py module"
  - "%PYTHON%\\python.exe setup.py test"
  - "%PYTHON%\\python.exe setup.py distclean"


