sudo: required
python: 3.6

language: C

matrix:
  include:
    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - sudo apt-get install valgrind
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make memcheck
        - python3 setup.py module
        - python3 setup.py test

    - compiler: clang
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - export CC=clang
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - ./configure
        - make check
        - python3 setup.py module
        - python3 setup.py test

    - compiler: gcc
      before_script:
        - git clone https://github.com/plures/ndtypes.git
        - cd ndtypes
        - python3 setup.py install --local=../python
        - cd ..
      script:
        - python3 setup.py build
        - python3 setup.py test

    - compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        - bash Miniconda3-latest-Linux-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - conda update --yes conda
        - conda install --yes conda-build
        - conda install --yes anaconda-client
        - conda install --yes -c plures/label/dev ndtypes
      script:
        - cd xnd
        - git fetch --unshallow
        - conda build .conda/libxnd -c plures/label/dev
        - conda build .conda/xnd -c plures/label/dev
        - export LIBXND=`conda build --output .conda/libxnd -c plures/label/dev`
        - export XND=`conda build --output .conda/xnd -c plures/label/dev`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBXND --user plures --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XND --user plures --label dev; fi

    - language: objective-c
      os: osx
      compiler: conda
      install:
        - cd ..
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        - bash Miniconda3-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda3/bin:$PATH
        - export CC=clang
        - conda update --yes conda
        - conda install --yes conda-build
        - conda install --yes anaconda-client
        - conda install --yes -c plures/label/dev ndtypes
      script:
        - cd xnd
        - git fetch --unshallow
        - conda build .conda/libxnd -c plures/label/dev
        - conda build .conda/xnd -c plures/label/dev
        - export LIBXND=`conda build --output .conda/libxnd -c plures/label/dev`
        - export XND=`conda build --output .conda/xnd -c plures/label/dev`
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $LIBXND --user plures --label dev; fi
        - if test X"$TRAVIS_BRANCH" = X"master" && test X"$TRAVIS_PULL_REQUEST" = X"false"; then anaconda --token $ANACONDA_TOKEN upload $XND --user plures --label dev; fi

env:
  global:
    - secure: "b8f55Y2maIiyYsVHtlkfzBl29PISiXuBL0D2AtNA+qodEtnVM24zxUfkLYddFUBgkqAlymMta6OuXZk8m41moxYhlVS/UBqwBKOIkRS/gwWjQEy4cnxBhsP6neD98ps70oxaw44vtgnI6qfWmHHsuR60NAAxfrpcG+yVlvNFgm2pKsaDifBkZFO5hZmr07qf8FnH/ejZ9ssKOACaKZnX4050uF7e9zfhFNLs23+1xQR7O9eFVr4gSJ6oaurjf0YsYabXRYZx+Ev9bIE7wXjbLPBYrMwr/3daA1MULfTeGOSGaxGaAMKQ5/J0NNqZbQO5pJZtgzi+SnBfZJ67F5/ji9b+6nGwkLcQiOtsId+qUxMGOSmQq/StkiY0K4Ch5dAMxouOAdJG04e3QB2l0f38/X45kRPoXBcUvbXJXxjadcOlhhNLp2mshXUkk06JxuGzbafuhX2MU4izDu2aHqNeh9kJnEZQ2dBMU775Yy6ERIHUE0VU32BZpe8XJ29ACkmeahTwi/f5m8kESwDEodaZCDAgNv+FL4Sv3jTh1s6nW8lmwfqbx2Faiw+v+Q2rm7NnIBodaQLZpj6A0AZf7Y08hU0vmTFI7ZHP2biPI08nmvKCL1WvrVqEnne4iwYimBqvSoV9ng7SflNYM66Fo0GIbf2CtcY+0JoQ9JO1dmUPao4="
